# Generated by Django 6.0.4 on 2026-04-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='견적명')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('sent', '발송'), ('accepted', '수주'), ('rejected', '실주')], default='draft', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='고객사')),
            ],
        ),
    ]
