# Generated by Django 6.0.4 on 2026-04-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'verbose_name': '견적', 'verbose_name_plural': '견적 목록'},
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='품목명')),
                ('price', models.IntegerField(verbose_name='단가')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.estimate')),
            ],
        ),
    ]
