# Generated by Django 6.0.4 on 2026-04-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_contact_options_and_more'),
        ('sales', '0002_alter_estimate_options_estimateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='currency',
            field=models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('CNY', '위안')], default='KRW', max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
